apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registy
          image: registry:2.8.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /var/lib/registry
              name: data
          resources:
            limits:
              memory: {{ .Values.registry.resources.limits.memory }}
        - name: registry-frontend
          image: konradkleine/docker-registry-frontend:v2
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: ENV_DOCKER_REGISTRY_HOST
              value: "localhost"
            - name: ENV_DOCKER_REGISTRY_PORT
              value: "5000"
          resources:
            limits:
              memory: {{ .Values.frontend.resources.limits.memory }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.registry.hostPath.data.path }}
