apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - name: registry
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.registry.nodePort }}
    - name: web-http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: {{ .Values.frontend.http.nodePort }}