apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
    version: 2.8.1
spec:
  selector:
    app: registry
    version: 2.8.1
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: {{ .Values.nodePort }}