apiVersion: v1
kind: Service
metadata:
  name: mssqlserver
  labels:
    app: mssqlserver
    version: "2022"
spec:
  selector:
    app: mssqlserver
    version: "2022"
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 1433
    targetPort: tcp
    nodePort: {{ .Values.nodePort }}
