apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-broker-conf
data:
  broker.conf: |-
    brokerClusterName = DefaultCluster
    brokerName = broker-a
    brokerId = 0
    deleteWhen = 04
    fileReservedTime = 48
    brokerRole = ASYNC_MASTER
    flushDiskType = ASYNC_FLUSH
    brokerIP1 = {{ .Values.rocketmq.ip }}