apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    version: 6.0.3
spec:
  selector:
    matchLabels:
      app: mongodb
      version: 6.0.3
  template:
    metadata:
      labels:
        app: mongodb
        version: 6.0.3
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.3
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.db.env.MONGO_INITDB_ROOT_USERNAME }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.db.env.MONGO_INITDB_ROOT_PASSWORD }}"
          resources:
            limits:
              memory: {{ .Values.db.resources.limits.memory }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: config
              mountPath: /data/configdb
            - name: db
              mountPath: /data/db
{{/*        - name: mongodb-express*/}}
{{/*          image: mongo-express:0.54.0*/}}
{{/*          ports:*/}}
{{/*            - name: web*/}}
{{/*              containerPort: 8081*/}}
{{/*          resources:*/}}
{{/*            limits:*/}}
{{/*              memory: {{ .Values.express.resources.limits.memory }}*/}}
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.hostPath.config.path }}
        - name: db
          hostPath:
            path: {{ .Values.hostPath.db.path }}
