apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    version: 6.0.3
spec:
  selector:
    app: mongodb
    version: 6.0.3
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: {{ .Values.nodePort }}