apiVersion: v1
kind: ConfigMap
metadata:
  name: xxljob-config
data:
  application.properties: |-
   spring.datasource.url=jdbc:mysql://{{ .Values.config.dbsvc }}:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
   spring.datasource.username={{ .Values.config.dbusername }}
   spring.datasource.password={{ .Values.config.dbpassword }}
   spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

   xxl.job.accessToken=123
   xxl.job.triggerpool.fast.max=200
   xxl.job.triggerpool.slow.max=100

   xxl.job.logretentiondays=7
