apiVersion: v1
kind: Service
metadata:
  labels:
    app: xxl-job-admin
    version: "2.2.0"
  name: xxl-job-admin
spec:
  selector:
    app: xxl-job-admin
    version: "2.2.0"
  type: NodePort
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
    nodePort: {{ .Values.nodePort }}
