apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  labels:
    app: nexus3
    version: 3
spec:
  selector:
    matchLabels:
      app: nexus3
      version: 3
  template:
    metadata:
      labels:
        app: nexus3
        version: 3
    spec:
      containers:
        - name: nexus3
          image: sonatype/nexus3.61.0
          ports:
            - name: web
              containerPort: 8081
            - name: host
              containerPort: 8082
            - name: group
              containerPort: 8083
          env:
            - name: NEXUS_CONTEXT
              value: "nexus"
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - mountPath: /nexus-data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /usr/volume/nexus3
            type: DirectoryOrCreate
