apiVersion: v1
kind: Service
metadata: 
  name: redis7
  labels:
    app: redis
    version: "7-alpine"
spec:
  selector:
    app: redis
    version: "7-alpine"
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: {{ .Values.nodePort }}
