apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  labels:
    app: graylog
    version: "4.3"
spec:
  selector:
    matchLabels:
      app: graylog
      version: "4.3"
  template:
    metadata:
      labels:
        app: graylog
        version: "4.3"
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:4.3
        env:
        - name: GRAYLOG_MONGODB_URI
          value: {{ .Values.env.GRAYLOG_MONGODB_URI }}
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: {{ .Values.env.GRAYLOG_ELASTICSEARCH_HOSTS }}
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: {{ .Values.env.GRAYLOG_HTTP_EXTERNAL_URI }}
        - name: GRAYLOG_ROOT_TIMEZONE
          value: {{ .Values.env.GRAYLOG_ROOT_TIMEZONE }}
        - name: GRAYLOG_PASSWORD_SECRET
          value: "{{ .Values.env.GRAYLOG_PASSWORD_SECRET }}"
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: {{ .Values.env.GRAYLOG_ROOT_PASSWORD_SHA2 }}
        ports:
        - name: web
          containerPort: 9000
        - name: syslog-tcp
          protocol: TCP
          containerPort: 1514
        - name: syslog-udp
          protocol: UDP
          containerPort: 1514
        - name: gelf-tcp
          protocol: TCP
          containerPort: 12201
        - name: gelf-udp
          protocol: UDP
          containerPort: 12201
        resources:
          limits:
{{/*            cpu: {{ .Values.resources.limits.cpu }}*/}}
            memory: {{ .Values.resources.limits.memory }}
