rocketmq:
  version: 4.8.0
  namesrv:
    env: 
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: -Xms128m -Xmx128m -Xmn64m
    resources:
      limits:
        memory: 256Mi
  broker:
    env: 
      TZ: Asia/Shanghai
      NAMESRV_ADDR: rocketmq:9876
      JAVA_OPT_EXT: -Xms128m -Xmx128m -Xmn64m
    resources:
      limits:
        memory: 256Mi

dashboard:
  version: 1.0.0
  nodePort: 48080
  JAVA_OPTS: -Xms128m -Xmx128m -Xmn64m -Drocketmq.namesrv.addr=rocketmq:9876
  resources:
    limits:
      memory: 256Mi

hostPath:
  logs:
    path: /usr/volume/rocketmq/logs
  store:
    path: /usr/volume/rocketmq/store