rocketmq:
  ip: 192.169.115.131
  version: 4.8.0
  namesrv:
    env: 
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: -Xms128m -Xmx128m -Xmn64m
    resources:
      limits:
        memory: 256Mi
  broker:
    env: 
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: -Xms128m -Xmx128m -Xmn64m
    resources:
      limits:
        memory: 256Mi

dashboard:
  version: 1.0.0
  env:
    JAVA_OPTS: -Xms128m -Xmx128m -Xmn64m
    namesrvAddr: rocketmq:9876
  resources:
    limits:
      memory: 256Mi
  nodePort: 48080

hostPath:
  logs:
    path: /usr/volume/rocketmq/logs
  store:
    path: /usr/volume/rocketmq/store