apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  selector:
    app: activemq
  type: NodePort
  ports:
  - name: webs
    port: 8161
    targetPort: 8161
    nodePort: 8161
  - name: mqtt
    port: 1883
    targetPort: 1883
    nodePort: 1883
  - name: "5672"
    port: 5672
    targetPort: 5672
    nodePort: 5672
  - name: "61613"
    port: 61613
    targetPort: 61613
    nodePort: 61613
  - name: "61614"
    port: 61614
    targetPort: 61614
    nodePort: 61614
  - name: "61616"
    port: 61616
    targetPort: 61616
    nodePort: 61616
