apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  ports:
    - name: web
      port: 8858
      protocol: TCP
      targetPort: web
      nodePort: {{ .Values.nodePort }}
    - name: heartbeat
      port: 8719
      protocol: TCP
      targetPort: heartbeat
      nodePort: 8719
