db:
  resources:
    limits:
      memory: 256Mi
  env:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: 123456
express:
  resources:
    limits:
      memory: 128Mi

hostPath:
  config:
    path: /usr/volume/mongodb/configdb
  db:
    path: /usr/volume/mongodb/db

nodePort:
  db: 27017
  express: 8081