env:
  discovery_type: single-node
  ES_JAVA_OPTS: -Xms128m -Xmx128m -Xmn64m
  TZ: Asia/Shanghai

resources:
  limits:
    cpu: 0.5
    memory: 256Mi

hostPath:
  data:
    path: /usr/volume/elasticsearch/data

nodePort:
  http: 9200
  tcp: 9300