env:
  discovery_type: single-node
  ES_JAVA_OPTS: -Xms256m -Xmx256m -Xmn128m
  TZ: Asia/Shanghai

resources:
  limits:
    cpu: 0.5
    memory: 384Mi

hostPath:
  data:
    path: /usr/volume/elasticsearch/data

nodePort:
  http: 9200
  tcp: 9300