apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  type: NodePort
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
      nodePort: {{ .Values.nodePort }}
    - name: leader
      port: 2888
      protocol: TCP
      targetPort: leader
    - name: comm
      port: 3888
      protocol: TCP
      targetPort: comm
