apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
    version: 1.14.4
spec:
  selector:
    app: consul
    version: 1.14.4
  type: NodePort
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
      nodePort: {{ .Values.nodePort }}
