apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    version: "7.17.8"
spec:
  selector:
    app: elasticsearch
    version: "7.17.8"
  type: NodePort
  ports:
    - name: http
      port: 9200
      targetPort: http
      nodePort: {{ .Values.nodePort.http }}
    - name: tcp
      port: 9300
      targetPort: tcp
      nodePort: {{ .Values.nodePort.tcp }}