apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    version: "15.1"
spec:
  selector:
    app: postgresql
    version: "15.1"
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: {{ .Values.nodePort }}