apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    version: 10.9.4
spec:
  selector:
    matchLabels:
      app: mariadb
      version: 10.9.4
  template:
    metadata:
      labels:
        app: mariadb
        version: 10.9.4
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.9.4
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "{{ .Values.env.MARIADB_ROOT_PASSWORD }}"
            - name: MARIADB_ROOT_HOST
              value: "{{ .Values.env.MARIADB_ROOT_HOST }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d
          resources:
            limits:
              memory: {{ .Values.resource.limits.memory }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.hostPath.data.path }}
        - name: config
          configMap:
            name: mariadb
