apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    version: 10.9.4
spec:
  selector:
    app: mariadb
    version: 10.9.4
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: {{ .Values.nodePort }}