apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  selector:
    app: nodered
  type: NodePort
  ports:
  - name: webs
    port: 1880
    targetPort: 1880
    nodePort: {{ .Values.nodePort.web }}
