apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofastdfs
  labels:
    app: gofastdfs
spec:
  selector:
    matchLabels:
      app: gofastdfs
  template:
    metadata:
      labels:
        app: gofastdfs
    spec:
      containers:
        - name: gofastdfs
          image: sjqzhang/go-fastdfs:v1.4.2
          ports:
            - name: server
              containerPort: 8080
        - name: fastdfsweb
          image: perfree/fastdfsweb:latest
          ports:
            - name: web
              containerPort: 8088
