apiVersion: v1
kind: Service
metadata:
  name: gofastdfs
  labels:
    app: gofastdfs
spec:
  type: NodePort
  selector:
    app: gofastdfs
  ports:
    - name: server
      protocol: TCP
      port: 8080
      targetPort: server
      nodePort: 18080
    - name: web
      protocol: TCP
      port: 8088
      targetPort: web
      nodePort: 8088