apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve=on
    max_connections=2000
    character-set-server=utf8mb4
    default-storage-engine=INNODB
    default-time-zone='+08:00'
    [mysql]
    default-character-set=utf8mb4
    [client]
    default-character-set=utf8mb4