apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  labels:
    app: "nacos-server"
    version: "v2.1.2"
spec:
  selector:
    matchLabels:
      app: "nacos-server"
      version: "v2.1.2"
  template:
    metadata:
      labels:
        app: "nacos-server"
        version: "v2.1.2"
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.1.2
        ports:
        - containerPort: 8848
        - containerPort: 9848
        env:
        - name: MODE
          value: "standalone"
        - name: JVM_XMS
          value: "{{ .Values.env.JVM_XMS }}"
        - name: JVM_XMX
          value: "{{ .Values.env.JVM_XMX }}"
        - name: JVM_XMN
          value: "{{ .Values.env.JVM_XMN }}"
        {{- if eq .Values.resources.enable true }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
        {{- end }}
